import GradedFrechetSpacesTameCanonicalLaneLean.Basic
import GradedFrechetSpacesTameCanonicalLaneLean.SourcePackage
import GradedFrechetSpacesTameCanonicalLaneLean.SourceDependencies
import GradedFrechetSpacesTameCanonicalLaneLean.Formalization
import GradedFrechetSpacesTameCanonicalLaneLean.ReviewerBridge
import GradedFrechetSpacesTameCanonicalLaneLean.TheoremStatement
import GradedFrechetSpacesTameCanonicalLaneLean.MathlibObjects
import GradedFrechetSpacesTameCanonicalLaneLean.AdmissibleClass
import GradedFrechetSpacesTameCanonicalLaneLean.Projection
import GradedFrechetSpacesTameCanonicalLaneLean.BridgeLemmas
import GradedFrechetSpacesTameCanonicalLaneLean.GateLemmas
import GradedFrechetSpacesTameCanonicalLaneLean.FinalTheorem
import GradedFrechetSpacesTameCanonicalLaneLean.GradedFrechetStructure
import GradedFrechetSpacesTameCanonicalLaneLean.TameCondition
import GradedFrechetSpacesTameCanonicalLaneLean.SteinInterpolation
import GradedFrechetSpacesTameCanonicalLaneLean.ProjectiveTensorProduct
import GradedFrechetSpacesTameCanonicalLaneLean.EndpointClassification
import GradedFrechetSpacesTameCanonicalLaneLean.AnalyticFoundation
import GradedFrechetSpacesTameCanonicalLaneLean.GradedRoute
import GradedFrechetSpacesTameCanonicalLaneLean.GradedAnalyticProof
import GradedFrechetSpacesTameCanonicalLaneLean.GradedAnalyticEvidenceTerms
import GradedFrechetSpacesTameCanonicalLaneLean.GradedFoundationalTheoremInhabitants
import GradedFrechetSpacesTameCanonicalLaneLean.GradedDeepAnalyticConstruction
import GradedFrechetSpacesTameCanonicalLaneLean.PrimitiveGradedFrechet
import GradedFrechetSpacesTameCanonicalLaneLean.MathlibFirstPrinciplesAnalyticBodies
import GradedFrechetSpacesTameCanonicalLaneLean.MathlibStatement

namespace HautevilleHouse
namespace GradedFrechetSpacesTameCanonicalLaneLean

-- Root module placeholder

def packageDescription : String :=
  "Graded Fréchet Spaces Tame — Canonical Lane Lean formalization"

end GradedFrechetSpacesTameCanonicalLaneLean
end HautevilleHouse
